name: Push to Google Apps Script (Sheet-bound)

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.clasp.json'
      - '.github/workflows/clasp-push.yml'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure workflow path
        run: |
          test -d .github/workflows || { echo "::error::Le workflow doit être dans .github/workflows/"; exit 1; }

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install clasp
        run: npm i -g @google/clasp

      - name: Write .clasprc.json from secret
        env:
          CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
        run: |
          test -n "$CLASPRC_JSON" || { echo "::error::Secret CLASPRC_JSON manquant"; exit 1; }
          cat > ~/.clasprc.json <<'JSON'
          $CLASPRC_JSON
          JSON
          node -e "JSON.parse(require('fs').readFileSync(process.env.HOME+'/.clasprc.json','utf8'))"

      - name: Show .clasp.json and rootDir sanity
        run: |
          test -f .clasp.json || { echo "::error::.clasp.json introuvable à la racine"; exit 1; }
          node -e "const j=require('./.clasp.json'); console.log('scriptId:',j.scriptId,'rootDir:',j.rootDir)"
          ROOTDIR=$(node -e "console.log(require('./.clasp.json').rootDir)")
          test -d "$ROOTDIR" || { echo "::error::Le dossier rootDir '$ROOTDIR' n'existe pas"; exit 1; }
          test -f "$ROOTDIR/appsscript.json" || { echo "::error::appsscript.json manquant dans $ROOTDIR"; exit 1; }
          echo "Contenu de $ROOTDIR :"; ls -la "$ROOTDIR"

      - name: Sanity .claspignore
        run: |
          ROOTDIR=$(node -e "console.log(require('./.clasp.json').rootDir)")
          test -f "$ROOTDIR/.claspignore" && { echo ".claspignore trouvé dans $ROOTDIR"; cat "$ROOTDIR/.claspignore"; } || { echo "::warning::.claspignore manquant dans $ROOTDIR (pas bloquant)"; }

      - name: Debug clasp status (avant push)
        run: clasp status || true

      - name: Push to Apps Script
        run: clasp push -f

      - name: Push to Apps Script
        run: clasp push -f
